import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import Navbar from "@/components/layout/app-navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sfCompact = localFont({
  src: [
    {
      path: "../public/fonts/SF Compact Text Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/SF Compact Text Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/SF Compact Text Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/SF Compact Text Semibold.woff2",
      weight: "656",
      style: "normal",
    },
    {
      path: "../public/fonts/SF Compact Text Bold.woff2",
      weight: "760",
      style: "normal",
    },
    {
      path: "../public/fonts/SF Compact Text Heavy.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-sf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sfCompact.variable} antialiased`}
      >
        <SidebarProvider>
          <Navbar />
          <AppSidebar />
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
